### PR TITLE
the way to output dimensions of sprites in newest version has changed

### PR DESCRIPTION
**Pull request by SUpermin6u**
in newest version, the example at 'examples/output-dimensions.md' couldn't work anymore, this id the correct way to output dimension

### CODE REVIEW

**Comment by vvasilev-** [comment]
According to [the API docs](http://api.postcss.org/Rule.html#insertAfter) of PostCSS this should work as expected. Also the test of the example is passed. Can you give more information when this isn't working?

**Comment by SUpermin6u** [comment]
I made some mistake, this happens when i import the "gulp-postcss" module to build the gulp work flow,and the config to use 'postcss-sprites' to output dimension is a little diffrent from the example you gave

**Comment by SUpermin6u** [comment]
I made some mistake, this happens when i import the "gulp-postcss" module to build the gulp work flow,and the config to use 'postcss-sprites' to output dimension is a little diffrent from the example you gave

**Comment by SUpermin6u** [comment]
I made some mistake, this happens when i import the "gulp-postcss" module to build the gulp work flow,and the config to use 'postcss-sprites' to output dimension is a little diffrent from the example you gave

**Comment by SUpermin6u** [comment]
I made some mistake, this happens when i import the "gulp-postcss" module to build the gulp work flow,and the config to use 'postcss-sprites' to output dimension is a little diffrent from the example you gave

**Comment by SUpermin6u** [comment]
I made some mistake, this happens when i import the "gulp-postcss" module to build the gulp work flow,and the config to use 'postcss-sprites' to output dimension is a little diffrent from the example you gave

**Comment by SUpermin6u** [comment]
I made some mistake, this happens when i import the "gulp-postcss" module to build the gulp work flow,and the config to use 'postcss-sprites' to output dimension is a little diffrent from the example you gave

**Comment by SUpermin6u** [comment]
I made some mistake, this happens when i import the "gulp-postcss" module to build the gulp work flow,and the config to use 'postcss-sprites' to output dimension is a little diffrent from the example you gave

**Comment by SUpermin6u** [comment]
I made some mistake, this happens when i import the "gulp-postcss" module to build the gulp work flow,and the config to use 'postcss-sprites' to output dimension is a little diffrent from the example you gave

**Pull request closed without merging**
