### PR TITLE
check build into source control

### LINKED ISSUE #51: Check build into source control
Having prepublish build into the ignored `lib` directory makes it difficult to fork the repo, dev on a branch, open a PR, and then point a project to the fork while waiting for the PR to merged upstream.

### PR DESCRIPTION
**Pull request by ianstarz**
fixes #51 

- removed `lib/` from `.gitignore`
- removed `src/` from `.npmignore`
- ran `npm run build`

This would be helpful for contributors so that they can fork, and try their forks out in their application before they open a PR, or use their forks in their application while awaiting a PR merge into upstream.

### CODE REVIEW

**Comment by vvasilev-** [comment]
You are right about that the source should be published to NPM but I don't see the reason to keep ``lib/`` folder under version control. The contributors will run the build and test the modified version of the plugin.

**Comment by ianstarz** [comment]
@vvasilev- the problem is when I have a fix for an issue that I want to use in my project, I can't point my project to my fork while I wait for my PR to be accepted to this repository. Maybe there's a better way of handling this aside from checking `lib` into source control?

**Comment by vvasilev-** [comment]
You can use [npm link](https://docs.npmjs.com/cli/link) to create a temporary alias to the fork and when your PR is accepted and published you can remove the alias.

**Comment by ianstarz** [comment]
that works if i'm the only one working on it, but my use case is working with a team and shipping production code via a build server. linking solution doesn't work well for that

**Comment by ianstarz** [comment]
after thinking it over, checking dist into source control would probably be annoying, maybe something like this could be a good solution? https://github.com/exogen/postinstall-build

**Pull request closed without merging**
